/**
 * Semantic icon keys — mirrors mobile/src/ui/icons/workflowIcons.js
 * Screens should use keys (e.g. "home.party"), not raw Lucide names.
 */
import {
  ArrowLeft,
  Award,
  Ban,
  Bell,
  Bookmark,
  BookOpen,
  Briefcase,
  Check,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  CloudOff,
  Copy,
  Download,
  Eye,
  FileText,
  Flag,
  GraduationCap,
  Heart,
  Highlighter,
  Home,
  Library,
  List,
  Lock,
  MapPin,
  Medal,
  Megaphone,
  Menu,
  MessageCircle,
  MessagesSquare,
  Moon,
  Pencil,
  Pin,
  Printer,
  Rocket,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Star,
  Sun,
  ThumbsUp,
  Trophy,
  User,
  Users,
  Wifi,
  WifiOff,
  X,
  XCircle,
} from 'lucide-react';

export const WORKFLOW_ICON_KEYS = {
  homePresidium: 'home.presidium',
  homeConstitution: 'home.constitution',
  homeAcademy: 'home.academy',
  homeLibrary: 'home.library',
  homeParty: 'home.party',
  homePartyOrgans: 'home.partyOrgans',
  homeChat: 'home.chat',
  homePriorityProjects: 'home.priorityProjects',
  homeTabHome: 'home.tab.home',
  homeTabConstitution: 'home.tab.constitution',
  homeTabChat: 'home.tab.chat',
  homeTabProfile: 'home.tab.profile',
  systemAnnouncement: 'system.announcement',
  systemBell: 'system.bell',
  systemOffline: 'system.offline',
  academyCourse: 'academy.course',
  academyMembership: 'academy.membership',
  academyAssessment: 'academy.assessment',
  academyAchievement: 'academy.achievement',
  academyBadge: 'academy.badge',
  certificateRibbon: 'certificate.ribbon',
  certificateDownload: 'certificate.download',
  certificateBanned: 'certificate.banned',
  navChevronForward: 'nav.chevronForward',
  navBack: 'nav.back',
  navMenu: 'nav.menu',
  systemCheck: 'system.check',
  systemFail: 'system.fail',
  dialogueChannel: 'dialogue.channel',
  dialogueChannelOfficial: 'dialogue.channelOfficial',
  dialogueThread: 'dialogue.thread',
  dialoguePinned: 'dialogue.pinned',
  dialogueLive: 'dialogue.live',
  actionSend: 'action.send',
  readerBookmark: 'reader.bookmark',
  readerCopy: 'reader.copy',
  readerPrint: 'reader.print',
  readerHighlight: 'reader.highlight',
  readerComment: 'reader.comment',
  readerDocument: 'reader.document',
  readerClose: 'reader.close',
  libraryDocument: 'library.document',
  bookmarksEmpty: 'bookmarks.empty',
  highlightsEmpty: 'highlights.empty',
  actionEdit: 'action.edit',
  priorityHeart: 'priority.heart',
  partyOrgan: 'party.organ',
  rolePresident: 'role.president',
  roleVicePresident: 'role.vicePresident',
  roleNationalChairperson: 'role.nationalChairperson',
  roleSecretaryGeneral: 'role.secretaryGeneral',
  roleFallback: 'role.fallback',
};

/** iconKey → Lucide component (closest semantic match to mobile Ionicons) */
export const WORKFLOW_ICONS = {
  // Home tiles
  'home.presidium': Users,
  'home.constitution': FileText,
  'home.academy': GraduationCap,
  'home.library': Library,
  'home.party': Flag,
  'home.partyOrgans': Shield,
  'home.chat': MessagesSquare,
  'home.priorityProjects': Rocket,

  // Home widgets
  'home.stats': ClipboardList,
  'home.trophy': Trophy,
  'home.location': MapPin,

  // Tab bar
  'home.tab.home': Home,
  'home.tab.constitution': FileText,
  'home.tab.chat': MessagesSquare,
  'home.tab.profile': User,

  // System / navigation
  'nav.chevronForward': ChevronRight,
  'nav.back': ArrowLeft,
  'nav.menu': Menu,
  'system.announcement': Megaphone,
  'system.bell': Bell,
  'system.offline': CloudOff,
  'system.alert': Megaphone,
  'system.check': CheckCircle,
  'system.fail': XCircle,
  'system.checkmark': Check,
  'system.forbidden': Lock,
  'system.networkOffline': WifiOff,

  // Academy (ready for section 2)
  'academy.course': BookOpen,
  'academy.membership': Award,
  'academy.assessment': ClipboardList,
  'academy.achievement': Medal,
  'academy.badge': Star,

  // Library
  'library.document': FileText,

  // Party
  'party.organ': Shield,

  // Dialogue
  'dialogue.channel': Users,
  'dialogue.channelOfficial': Users,
  'dialogue.thread': MessageCircle,
  'dialogue.pinned': Pin,
  'dialogue.live': Wifi,
  'action.send': Send,

  // Certificates
  'certificate.ribbon': Award,
  'certificate.download': Download,
  'certificate.banned': Ban,

  // Reader
  'reader.bookmark': Bookmark,
  'reader.copy': Copy,
  'reader.share': Share2,
  'reader.highlight': Highlighter,
  'reader.comment': MessageCircle,
  'reader.document': FileText,
  'reader.print': Printer,
  'reader.arrowBack': ArrowLeft,
  'reader.chevronBack': ChevronLeft,
  'reader.chevronForward': ChevronRight,
  'reader.settings': Settings,
  'reader.moon': Moon,
  'reader.sunny': Sun,
  'reader.eye': Eye,
  'reader.toc': List,
  'reader.close': X,
  'bookmarks.empty': Bookmark,
  'highlights.empty': Pencil,
  'action.edit': Pencil,

  // Priority
  'priority.like': ThumbsUp,
  'priority.heart': Heart,
  'priority.rocket': Rocket,

  // Roles
  'role.president': Award,
  'role.vicePresident': ShieldCheck,
  'role.nationalChairperson': Users,
  'role.secretaryGeneral': Briefcase,
  'role.fallback': User,
};

export function getWorkflowIcon(iconKey) {
  return WORKFLOW_ICONS[iconKey] ?? FileText;
}
