<?php

namespace Database\Seeders;

use App\Models\StaticPage;
use Illuminate\Database\Seeder;

class StaticPagesSeeder extends Seeder
{
    public function run(): void
    {
        $defaults = [
            [
                'slug' => 'help',
                'title' => 'Help & Support',
                'body' => implode("\n\n", [
                    'Welcome to the ZANU PF Constitutional Education & Academy app. This Help & Support page explains how to use the main features, how your information is used, and how to get assistance when you need it.',
                    '1. Getting started',
                    '- Use the Overview screen (Home) to see a quick snapshot of your learning status, dialogue activity, and priority projects that support Vision 2030.',
                    '- Tap the bottom navigation bar to move between Home, Constitutions, Dialogue (chat), and your Profile.',
                    '- If you are new, register with accurate personal details so that certificates and membership records are issued in your correct name.',
                    '2. Studying the Constitutions',
                    '- The Constitutions section gives you a structured reader for both the ZANU PF Constitution and the Constitution of Zimbabwe.',
                    '- You can navigate by Parts, Chapters, and Sections, and follow references from Presidium, Party Organs, Priority Projects and other screens back to the relevant constitutional provisions.',
                    '- Use this reader as your primary reference when preparing for Academy assessments or internal party discussions.',
                    '3. Academy and certificates',
                    '- The Academy hosts formal learning programmes. Each course has modules, assessments and, where applicable, a certificate on completion.',
                    '- Your Home overview shows your current enrolments, assessments completed and whether you have an issued membership certificate.',
                    '- Badges and achievements recognise key milestones (for example course completion, high scores, or membership status) and are visible in your Profile.',
                    '4. Dialogue (Opinion & Engagement)',
                    '- The Dialogue section allows structured conversations with the Presidium and Party Leagues on specific topics.',
                    '- Official responses from Editors or Presidium representatives are clearly marked in the interface, so that members can distinguish them from general comments.',
                    '- Please follow party protocols when participating in dialogue: be respectful, avoid personal attacks, and keep discussions aligned with party policy and constitutional values.',
                    '5. Priority projects',
                    '- Priority Projects highlight programmes and initiatives aligned with Vision 2030 and other key strategic goals.',
                    '- You can read the full details of each project and indicate your support by liking a project once.',
                    '- Likes and engagement help leadership understand which projects resonate most with members and where to focus communication and resources.',
                    '6. Help, Terms & Privacy',
                    '- This Help page provides an overview of how to use the system.',
                    '- The Terms & Conditions page sets out how you are expected to use the app and your responsibilities as a member or learner.',
                    '- The Privacy Policy explains what data is collected, how it is stored, and how it may be used for party and educational purposes.',
                    '7. Getting support',
                    '- If you have problems logging in, seeing your courses, or accessing certificates, first confirm your network connection and try signing out and back in.',
                    '- For account-related issues (such as incorrect name, missing certificates, or membership records), contact your District or Provincial leadership, who can escalate to the system administrator.',
                    '- For technical issues (for example, errors in the app, missing content, or incorrect constitutional references), inform your local ICT focal person or send details, screenshots and your device type to the designated party ICT support channel.',
                    '8. Responsible use',
                    '- Use this application only for lawful party and educational purposes. Do not share your login with others or post confidential information outside approved channels.',
                    '- Treat this platform as an official record of your learning and engagement. The quality of data and discussions here informs Presidium and leadership decisions.',
                ]),
            ],
            [
                'slug' => 'terms',
                'title' => 'Terms & Conditions',
                'body' => implode("\n\n", [
                    'These Terms & Conditions govern your use of the ZANU PF Constitutional Education & Academy application. By accessing or using this app, you agree to be bound by these terms and to uphold the values and obligations of the Party and the Constitutions.',
                    '1. Purpose of the application',
                    '- This app exists to support constitutional literacy, structured political education, internal communication and organisational discipline within ZANU PF.',
                    '- It is not a public social media platform. It is an internal tool of the Party and must be used accordingly.',
                    '2. Eligibility and account responsibility',
                    '- You must provide accurate personal details when registering so that certificates, membership records and achievements are correctly issued.',
                    '- You are responsible for maintaining the confidentiality of your login credentials and for all activities carried out under your account.',
                    '- If you suspect that your account has been compromised, you must notify appropriate Party structures or the system administrator as soon as possible.',
                    '3. Acceptable use',
                    '- Use the app only for lawful purposes and for activities consistent with Party policy, the ZANU PF Constitution and the Constitution of Zimbabwe.',
                    '- Do not upload, post or share content that is defamatory, hateful, incites violence, or undermines the unity and discipline of the Party.',
                    '- Do not attempt to interfere with the operation of the system, bypass security controls, or gain unauthorised access to data.',
                    '4. Dialogue and communication standards',
                    '- Engage in Dialogue channels respectfully and constructively. Criticism and debate must be issue-based and aligned with party protocols.',
                    '- Respect the confidentiality of internal discussions and do not share sensitive information outside authorised party channels.',
                    '- Official responses from Editors or Presidium representatives are clearly marked; do not impersonate officials or misrepresent your role.',
                    '5. Learning, assessments and certificates',
                    '- You agree to complete Academy assessments honestly and without cheating or misrepresentation.',
                    '- Certificates and badges issued through this app reflect your recorded learning activity and may be used for internal recognition and organisational planning.',
                    '- Any attempt to falsify assessment results, certificates or membership records is a serious disciplinary offence.',
                    '6. Intellectual property and content',
                    '- Course materials, constitutional content, branding and other resources provided in the app are for your personal educational use within the Party.',
                    '- You may not copy, redistribute or modify this content for external use without proper authorisation.',
                    '7. Suspension and termination',
                    '- The Party may suspend or terminate access to this app if you breach these terms, abuse the platform, or act in a manner inconsistent with Party discipline.',
                    '- Suspension or termination may affect your ability to participate in certain programmes or to access certificates and records until the matter is resolved.',
                    '8. Changes to the app and these terms',
                    '- Features of the app may be updated or adjusted from time to time as the Party refines its digital tools and educational strategy.',
                    '- These Terms & Conditions may also be updated. Material changes will be approved through appropriate internal structures and published in this section.',
                    '9. Acceptance',
                    '- By continuing to use this application, you confirm that you understand these Terms & Conditions and agree to be bound by them.',
                    '- If you do not agree, you must refrain from using the app and seek guidance from your District or Provincial leadership.',
                ]),
            ],
            [
                'slug' => 'privacy',
                'title' => 'Privacy Policy',
                'body' => implode("\n\n", [
                    'This Privacy Policy explains how the ZANU PF Constitutional Education & Academy app collects, uses and protects your information when you use this system.',
                    '1. Information we collect',
                    '- Identification: your name, surname, contact details and (where captured) party membership details needed to correctly issue certificates and records.',
                    '- Account data: username, email address, password hash, roles and permissions that determine what you can see and do in the system.',
                    '- Learning data: course enrolments, assessments attempted, scores, badges earned, certificates issued and related timestamps.',
                    '- Engagement data: participation in Dialogue channels (messages you send, topics you view), likes on Priority Projects, and basic usage information such as last login time.',
                    '2. How we use your information',
                    '- To operate the Academy and certificate system, including tracking your progress, issuing certificates, and confirming membership or competence where applicable.',
                    '- To support structured Dialogue with the Presidium and Party Leagues, including moderation, audit trails and analytics on engagement.',
                    '- To improve party education programmes by understanding which courses, projects and topics are most used and where members might need additional support.',
                    '- To protect the security of the system, detect misuse, and enforce party and constitutional obligations regarding responsible use.',
                    '3. How your information is stored and protected',
                    '- Data is stored in secured databases with access restricted to authorised party officials, system administrators and approved support personnel.',
                    '- Passwords are stored in hashed form; they are not visible in plain text to administrators.',
                    '- Regular backups and technical safeguards (such as access control, logging and monitoring) are applied to reduce the risk of data loss or unauthorised access.',
                    '4. When information may be shared',
                    '- Within the Party: relevant information (such as your learning status, certificates and dialogue contributions) may be shared with your District, Provincial and National leadership for organisational planning and reporting.',
                    '- With service providers: technical partners supporting hosting, development or maintenance may have controlled access to data strictly for operational purposes and under confidentiality obligations.',
                    '- When required by law: information may be disclosed if required by applicable law, court order, or internal party disciplinary processes consistent with the Constitutions.',
                    '5. Your responsibilities and choices',
                    '- Keep your login details confidential and do not share your account with others.',
                    '- Ensure the personal details you provide are accurate so that certificates and records are correct.',
                    '- Use Dialogue and other engagement features in accordance with party policy and avoid posting sensitive information that should be handled through official channels.',
                    '6. Data retention',
                    '- Learning, membership and engagement records may be retained for as long as necessary to support party programmes, historical analysis and compliance with party and legal obligations.',
                    '- Where appropriate and subject to policy, certain data may be anonymised and used in aggregate for reporting and planning.',
                    '7. Changes to this policy',
                    '- The Party may update this Privacy Policy from time to time to reflect new features, legal requirements or organisational decisions.',
                    '- Any material changes will be approved through the appropriate internal structures and made available within this app.',
                    'If you have questions about how your data is handled in this system, please raise them through your District or Provincial leadership, who can escalate to the responsible national office or system administrator.',
                ]),
            ],
            [
                'slug' => 'cookies',
                'title' => 'Cookie Policy',
                'body' => implode("\n\n", [
                    'This Cookie Policy explains how cookies and similar storage are used within this platform.',
                    '1. What cookies are used for',
                    '- Authentication and session management.',
                    '- Security protections (for example CSRF protection).',
                    '- Remembering certain preferences to improve your experience.',
                    '2. Local preferences storage',
                    '- The app may store small preference values (such as theme settings) to keep the experience consistent.',
                    '3. Managing cookies',
                    '- You can clear cookies and site data from your device or browser settings.',
                    '- Clearing cookies may sign you out and require you to sign in again.',
                ]),
            ],
            [
                'slug' => 'settings',
                'title' => 'Settings & Preferences',
                'body' => implode("\n\n", [
                    'The Settings & Preferences section allows you to review key information about your account and adjust how you interact with the app, in line with party policy and security guidelines.',
                    '1. Your profile details',
                    '- Check that your name, surname and any membership identifiers are correct. These details are used on certificates, membership records and reports.',
                    '- If you notice an error in your official details, do not try to create a second account. Instead, inform your District or Provincial leadership so that they can request a correction through the appropriate structures.',
                    '2. Security and access',
                    '- Always use a strong, private password. Avoid reusing passwords from social media or personal accounts.',
                    '- Do not share your login details with friends, family or colleagues. Your activity in the app forms part of your individual record.',
                    '- If you sign in on a shared or public device, remember to sign out when you finish and, where possible, avoid saving your password in the browser.',
                    '3. Notifications and communication',
                    '- Where notification settings are available, use them to ensure you are alerted to important updates, such as new courses, dialogue threads or priority projects.',
                    '- Even if you reduce certain notifications, you remain responsible for staying informed about key announcements from the Party and the Presidium.',
                    '4. Using the app responsibly',
                    '- Review the Terms & Conditions and Privacy Policy regularly so that you remain aware of your responsibilities and how your data is handled.',
                    '- Treat the app as an official channel of the Party. What you do here may be considered in organisational planning, recognition and discipline.',
                    'If you need assistance with a setting you cannot change yourself, please raise it with your local leadership, who can coordinate with the system administrator.',
                ]),
            ],
        ];

        foreach ($defaults as $data) {
            StaticPage::updateOrCreate(
                ['slug' => $data['slug']],
                [
                    'title' => $data['title'],
                    'body' => $data['body'],
                    'is_published' => true,
                ]
            );
        }
    }
}

